//! Write deterministic draft section files for agents.

use std::fs;
use std::path::Path;

use camino::{Utf8Path, Utf8PathBuf};

use crate::error::LatexError;
use crate::sections::{TexSection, split_tex_sections};

/// Metadata for one section file written under the draft sections directory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WrittenSection {
    /// 0-based index in split order.
    pub index: usize,
    /// Relative file name inside the sections directory (e.g. `01-introduction.tex`).
    pub filename: String,
    /// Absolute path written.
    pub path: Utf8PathBuf,
    /// Section title from the draft.
    pub title: String,
    /// Heading kind (`section`, `subsection`, …).
    pub kind: String,
}

/// Slugify a section title for a stable, filesystem-safe filename component.
pub fn slugify_title(title: &str) -> String {
    let mut out = String::new();
    let mut prev_dash = false;
    for ch in title.chars() {
        let lower = ch.to_ascii_lowercase();
        if lower.is_ascii_alphanumeric() {
            out.push(lower);
            prev_dash = false;
        } else if !prev_dash && !out.is_empty() {
            out.push('-');
            prev_dash = true;
        }
    }
    let trimmed = out.trim_matches('-').to_string();
    if trimmed.is_empty() {
        "section".into()
    } else {
        // Cap length for path safety
        trimmed.chars().take(48).collect::<String>().trim_end_matches('-').to_string()
    }
}

/// Stable section filename: `{nn}-{slug}.tex` (1-based index, zero-padded).
pub fn section_filename(index: usize, title: &str) -> String {
    format!("{:02}-{}.tex", index + 1, slugify_title(title))
}

/// Split `draft_tex` and rewrite `out_dir` with one file per section.
///
/// - Creates `out_dir` if missing.
/// - Removes previous `*.tex` and `index.md` under `out_dir` before writing
///   (does not delete unrelated files outside that pattern).
/// - Does **not** modify the original draft source.
/// - Writes an `index.md` listing sections for agents.
///
/// Returns the list of written section files in order.
pub fn write_draft_sections(
    draft_tex: &str,
    out_dir: &Utf8Path,
) -> Result<Vec<WrittenSection>, LatexError> {
    fs::create_dir_all(out_dir.as_str()).map_err(|source| LatexError::Io {
        path: out_dir.to_string(),
        source,
    })?;

    clear_section_artifacts(out_dir)?;

    let sections = split_tex_sections(draft_tex);
    let mut written = Vec::with_capacity(sections.len());
    let mut used_names = std::collections::HashSet::new();

    for (i, sec) in sections.iter().enumerate() {
        let mut filename = section_filename(i, &sec.title);
        // Disambiguate rare slug collisions
        if used_names.contains(&filename) {
            filename = format!("{:02}-{}-{}.tex", i + 1, slugify_title(&sec.title), i);
        }
        used_names.insert(filename.clone());

        let path = out_dir.join(&filename);
        let content = format_section_file(sec, i);
        fs::write(path.as_str(), content).map_err(|source| LatexError::Io {
            path: path.to_string(),
            source,
        })?;
        written.push(WrittenSection {
            index: i,
            filename,
            path,
            title: sec.title.clone(),
            kind: sec.kind.clone(),
        });
    }

    write_index_md(out_dir, &written, &sections)?;
    Ok(written)
}

/// Read `paper_draft.tex` from disk and write section files under `out_dir`.
///
/// Returns `(original_draft_bytes_unchanged_check_path, written sections)`.
/// The draft file is only read — never written.
pub fn write_draft_sections_from_file(
    draft_path: &Utf8Path,
    out_dir: &Utf8Path,
) -> Result<(String, Vec<WrittenSection>), LatexError> {
    let draft = fs::read_to_string(draft_path.as_str()).map_err(|source| LatexError::Io {
        path: draft_path.to_string(),
        source,
    })?;
    let written = write_draft_sections(&draft, out_dir)?;
    Ok((draft, written))
}

fn format_section_file(sec: &TexSection, index: usize) -> String {
    let mut out = String::new();
    out.push_str("% AUTO-GENERATED by `sil split` — do not treat as source of truth.\n");
    out.push_str("% Edit paper_draft.tex instead, then re-run `sil split`.\n");
    out.push_str(&format!(
        "% kind={} title={:?} line_start={} index={}\n",
        sec.kind, sec.title, sec.line_start, index
    ));
    out.push_str(&format!("\\{}{{{}}}\n", sec.kind, sec.title));
    if !sec.body.is_empty() {
        out.push_str(&sec.body);
        if !sec.body.ends_with('\n') {
            out.push('\n');
        }
    }
    out
}

fn write_index_md(
    out_dir: &Utf8Path,
    written: &[WrittenSection],
    sections: &[TexSection],
) -> Result<(), LatexError> {
    let mut md = String::from(
        "# Draft sections (agent cache)\n\n\
         Generated from `paper_draft.tex` by `sil split`. \
         **Source of truth is still `paper_draft.tex`.**\n\n\
         | # | file | kind | title | line |\n\
         |---|------|------|-------|------|\n",
    );
    for (w, sec) in written.iter().zip(sections.iter()) {
        md.push_str(&format!(
            "| {} | `{}` | {} | {} | {} |\n",
            w.index + 1,
            w.filename,
            sec.kind,
            sec.title.replace('|', "\\|"),
            sec.line_start
        ));
    }
    let path = out_dir.join("index.md");
    fs::write(path.as_str(), md).map_err(|source| LatexError::Io {
        path: path.to_string(),
        source,
    })?;
    Ok(())
}

fn clear_section_artifacts(out_dir: &Utf8Path) -> Result<(), LatexError> {
    let entries = match fs::read_dir(out_dir.as_str()) {
        Ok(e) => e,
        Err(source) => {
            return Err(LatexError::Io {
                path: out_dir.to_string(),
                source,
            });
        }
    };
    for entry in entries {
        let entry = entry.map_err(|source| LatexError::Io {
            path: out_dir.to_string(),
            source,
        })?;
        let path = entry.path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        let remove = name == "index.md"
            || Path::new(name)
                .extension()
                .and_then(|e| e.to_str())
                .map(|e| e.eq_ignore_ascii_case("tex"))
                .unwrap_or(false);
        if remove {
            fs::remove_file(&path).map_err(|source| LatexError::Io {
                path: path.display().to_string(),
                source,
            })?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn slugify_basic() {
        assert_eq!(slugify_title("Introduction"), "introduction");
        assert_eq!(slugify_title("Related Work"), "related-work");
        assert_eq!(slugify_title("  Foo   Bar!! "), "foo-bar");
        assert_eq!(slugify_title("???"), "section");
    }

    #[test]
    fn section_filename_padded() {
        assert_eq!(
            section_filename(0, "Introduction"),
            "01-introduction.tex"
        );
        assert_eq!(section_filename(9, "Methods"), "10-methods.tex");
    }

    #[test]
    fn write_preserves_draft_and_creates_files() {
        let dir = tempfile::tempdir().unwrap();
        let root = Utf8PathBuf::from_path_buf(dir.path().to_path_buf()).unwrap();
        let draft_path = root.join("paper_draft.tex");
        let out_dir = root.join(".sil/draft_sections");
        let draft = r#"\documentclass{article}
\begin{document}
\section{Introduction}
Hello intro.

\section{Methods}
We did science.
\end{document}
"#;
        fs::write(draft_path.as_str(), draft).unwrap();
        let before = fs::read_to_string(draft_path.as_str()).unwrap();

        let (read_back, written) =
            write_draft_sections_from_file(&draft_path, &out_dir).unwrap();
        assert_eq!(read_back, before);
        assert_eq!(
            fs::read_to_string(draft_path.as_str()).unwrap(),
            before,
            "original draft must be unchanged"
        );
        assert_eq!(written.len(), 2);
        assert!(written[0].filename.starts_with("01-"));
        assert!(written[0].title == "Introduction");
        assert!(written[1].title == "Methods");

        let intro = fs::read_to_string(written[0].path.as_str()).unwrap();
        assert!(intro.contains("Hello intro"));
        assert!(intro.contains("\\section{Introduction}"));
        assert!(intro.contains("AUTO-GENERATED"));

        let methods = fs::read_to_string(written[1].path.as_str()).unwrap();
        assert!(methods.contains("We did science"));

        assert!(out_dir.join("index.md").is_file());
        let index = fs::read_to_string(out_dir.join("index.md").as_str()).unwrap();
        assert!(index.contains("Introduction"));
        assert!(index.contains("Methods"));
    }

    #[test]
    fn second_run_is_consistent_and_refreshes() {
        let dir = tempfile::tempdir().unwrap();
        let out = Utf8PathBuf::from_path_buf(dir.path().join("secs")).unwrap();
        let draft_v1 = "\\section{A}\na1\n\\section{B}\nb1\n";
        let w1 = write_draft_sections(draft_v1, &out).unwrap();
        assert_eq!(w1.len(), 2);

        let draft_v2 = "\\section{A}\na2-updated\n\\section{B}\nb2\n\\section{C}\nc\n";
        let w2 = write_draft_sections(draft_v2, &out).unwrap();
        assert_eq!(w2.len(), 3);
        let a = fs::read_to_string(out.join("01-a.tex").as_str()).unwrap();
        assert!(a.contains("a2-updated"));
        assert!(!a.contains("a1"));
        assert!(out.join("03-c.tex").is_file());
        // Stale count: only 3 tex files
        let tex_count = fs::read_dir(out.as_str())
            .unwrap()
            .filter(|e| {
                e.as_ref()
                    .ok()
                    .and_then(|e| e.path().extension().map(|x| x == "tex"))
                    .unwrap_or(false)
            })
            .count();
        assert_eq!(tex_count, 3);
    }

    #[test]
    fn empty_document_one_file() {
        let dir = tempfile::tempdir().unwrap();
        let out = Utf8PathBuf::from_path_buf(dir.path().join("s")).unwrap();
        let w = write_draft_sections("just text no sections", &out).unwrap();
        assert_eq!(w.len(), 1);
        assert!(w[0].kind == "document");
        let body = fs::read_to_string(w[0].path.as_str()).unwrap();
        assert!(body.contains("just text no sections"));
    }
}
